ALTER TABLE event DROP CONSTRAINT event_category_check;

ALTER TABLE event ADD CONSTRAINT event_category_check 
CHECK (category IN ('MUSIC', 'SPORTS', 'ART', 'FOOD', 'TECHNOLOGY', 'PARTY', 'ENTERTAINMENT', 'EDUCATION', 'NETWORKING', 'HEALTH', 'OUTDOOR', 'CHARITY', 'GAMES', 'OTHER'));